Footer
istc-sce/ISETechClub pull request #42
Opened 2020-10-25 14:47 UTC by pranavbharadwaj007

Simple footer

2020-10-25 16:21 UTC, istc-sce requested changes

2020-10-25 16:21 UTC, istc-sce commented on src/components/footer.js
> +                              <a href="https://www.instagram.com/istcsce/?igshid=auqnvolgbjii">
Open the links in new tab. We dont want the user to leave our site.

2020-10-25 16:21 UTC, istc-sce commented on src/components/footer.js
> +               <a href="https://github.com/niranjanhegde144/ISETechClub">
Change repo link, and open in new tab

2020-10-25 16:21 UTC, istc-sce commented on src/components/footer.js
> +                  <a href="https://www.linkedin.com/company/is-technical-club-sce"><FontAwesomeIcon
Open in new tab.

2020-10-25 16:21 UTC, istc-sce commented on src/components/footer.js
> +            </Link>
We are working on something, so we wont have this /programming link available.

So for now you can just comment this part, and edit it post those changes.

2020-10-25 16:21 UTC, istc-sce commented on src/components/footer.js
> +                                /> istcsce@gmail.com</h3>
use "mailto:" here.

2020-10-25 16:21 UTC, istc-sce commented on src/components/footer.js
> +export default Footer;
Check the mobile view of footer as well. Need to do some fixes for that.

2020-10-27 13:15 UTC, niranjanhegde144 commented on src/App.css
> +    font-family: "Montserrat", sans-serif;
Font family is not required remove it.

2020-10-27 13:16 UTC, niranjanhegde144 commented on src/App.css
> +    font-family: "Montserrat", sans-serif;
Remove font family everywhere.

2020-10-28 13:52 UTC, akramkazmi71 commented on src/components/footer.js
> +                                /> istcsce@gmail.com</h3>
You missed this comment, I guess.

2020-10-29 05:49 UTC, akramkazmi71 requested changes

2020-10-29 05:49 UTC, akramkazmi71 commented on src/components/footer.js
> +                                /> mailto: istcsce@gmail.com</h3>
'mailto' is referred to this:
`<a href = "mailto: istcsce@gmail.com">istcsce@gmail.com</a>`

2020-10-29 06:50 UTC, merged